/**
 * TOFU enrollment — exchange + pin long-term Ed25519 identities over the ALREADY-AUTHENTICATED
 * DataChannel (step 4b-i).
 *
 * Trust model: enrollment runs ONLY after `connected`, i.e. after SAS (room) or CPace +
 * key-confirmation (words) has already beaten any MITM. So exchanging public keys over the
 * channel is trustworthy — this is the trust-on-first-use moment, bootstrapped by the human/PAKE
 * check that already happened. Enrollment is therefore an ACTION on entering `connected`, not a
 * new FSM state and not a gate: files flow regardless, and a bad enrollment signature does NOT
 * tear the (human-authenticated) session down — it just declines to pin.
 *
 * Each side signs its OWN public key over a transcript bound to:
 *   - a fixed domain label,
 *   - the per-pair `pairingId` (16 random bytes the INITIATOR generates — a key-INDEPENDENT
 *     stable id, so 4b-ii can re-present the same pairingId under a DIFFERENT key and detect a
 *     swap; deriving the id from the key would make a key change indistinguishable from a new pair),
 *   - the two DTLS fingerprints (canonical sorted order — the SAME channel binding as
 *     keyConfirmation/sas, parsed from the negotiated SDP), and
 *   - a role label (initiator/responder).
 *
 *   sign( lv("hushsend/identity/enroll") || lv(pairingId) || lv(ownPubKey)
 *         || lv(fp_min) || lv(fp_max) || lv(role) )
 *
 * Because each side signs its own key, a side can sign and send immediately — it never waits for
 * the peer's key. The verifier reconstructs the transcript with the RECEIVED pubKey as the
 * signer's ownPubKey, the PEER's role, the shared pairingId, and its own (canonicalised)
 * fingerprints — binding the enrollment to this exact channel. This is the same lv + fp
 * canonicalisation 4b-ii will reuse for reconnect signatures.
 */
import { z } from 'zod';
import { concatBytes, utf8ToBytes } from '@noble/hashes/utils.js';
import { verifySignature, type IdentityKey } from './identity';
import type { ConfirmationRole } from './keyConfirmation';

/** pairingId length (bytes): 16 random bytes from a CSPRNG, generated by the initiator. */
export const PAIRING_ID_BYTES = 16;
/** Ed25519 public key / signature byte lengths — pinned exactly in the wire schema below. */
const PUBKEY_BYTES = 32;
const SIG_BYTES = 64;

/** Domain separation for the enrollment transcript (distinct from cpace/confirm and sas). */
const ENROLL_DOMAIN = utf8ToBytes('hushsend/identity/enroll');

/** Length-value prefix (1-byte-granular LEB128) — identical to keyConfirmation/sas. */
function lv(data: Uint8Array): Uint8Array {
  const prefix: number[] = [];
  let length = data.length;
  for (;;) {
    if (length < 128) prefix.push(length);
    else prefix.push((length & 0x7f) + 0x80);
    length = Math.floor(length / 128);
    if (length === 0) break;
  }
  return concatBytes(Uint8Array.from(prefix), data);
}

/**
 * Build the enrollment signature transcript. The two fingerprints are bound in CANONICAL
 * (lexicographic) order — the channel binding — so both peers, holding the same pair labelled
 * local/remote oppositely, produce identical bytes for a given (pairingId, ownPubKey, role).
 */
export function enrollmentTranscript(
  pairingId: Uint8Array,
  ownPublicKey: Uint8Array,
  localFingerprint: string,
  remoteFingerprint: string,
  role: ConfirmationRole,
): Uint8Array {
  const [fpMin, fpMax] =
    localFingerprint <= remoteFingerprint
      ? [localFingerprint, remoteFingerprint]
      : [remoteFingerprint, localFingerprint];
  return concatBytes(
    lv(ENROLL_DOMAIN),
    lv(pairingId),
    lv(ownPublicKey),
    lv(utf8ToBytes(fpMin)),
    lv(utf8ToBytes(fpMax)),
    lv(utf8ToBytes(role)),
  );
}

/** Sign our OWN public key into the channel-bound transcript for `role`. */
export function signEnrollment(
  identity: IdentityKey,
  pairingId: Uint8Array,
  localFingerprint: string,
  remoteFingerprint: string,
  role: ConfirmationRole,
): Promise<Uint8Array> {
  return identity.sign(
    enrollmentTranscript(pairingId, identity.publicKey, localFingerprint, remoteFingerprint, role),
  );
}

/**
 * Verify a peer's enrollment signature: reconstruct the transcript with `peerPublicKey` as the
 * signer's ownPubKey and `peerRole` as the role, using our own (canonicalised) fingerprints.
 */
export function verifyEnrollment(
  peerPublicKey: Uint8Array,
  pairingId: Uint8Array,
  localFingerprint: string,
  remoteFingerprint: string,
  peerRole: ConfirmationRole,
  signature: Uint8Array,
): Promise<boolean> {
  return verifySignature(
    peerPublicKey,
    enrollmentTranscript(pairingId, peerPublicKey, localFingerprint, remoteFingerprint, peerRole),
    signature,
  );
}

// --- enrollment wire frames (over the DataChannel, NOT file bytes) -----------------------------
// The DataChannel is already authenticated, but the frames are still validated with EXACT decoded
// lengths (pairingId 16 B, pubKey 32 B, sig 64 B) so a malformed control message is rejected
// before it reaches the crypto. Hex ⇒ exactly 2× those byte counts of [0-9a-fA-F].
const HEX = /^(?:[0-9a-fA-F]{2})*$/;
const PAIRING_ID_HEX = PAIRING_ID_BYTES * 2;
const PUBKEY_HEX = PUBKEY_BYTES * 2;
const SIG_HEX = SIG_BYTES * 2;

/** Initiator → responder: carries the pairingId (initiator-chosen), the initiator's pubkey + sig. */
export const enrollInitSchema = z.object({
  kind: z.literal('enroll-init'),
  pairingId: z.string().regex(HEX).length(PAIRING_ID_HEX),
  pubKey: z.string().regex(HEX).length(PUBKEY_HEX),
  sig: z.string().regex(HEX).length(SIG_HEX),
});

/** Responder → initiator: the responder's pubkey + sig (pairingId is already known to the initiator). */
export const enrollAckSchema = z.object({
  kind: z.literal('enroll-ack'),
  pubKey: z.string().regex(HEX).length(PUBKEY_HEX),
  sig: z.string().regex(HEX).length(SIG_HEX),
});

export const enrollFrameSchema = z.discriminatedUnion('kind', [enrollInitSchema, enrollAckSchema]);
export type EnrollInit = z.infer<typeof enrollInitSchema>;
export type EnrollAck = z.infer<typeof enrollAckSchema>;
export type EnrollFrame = z.infer<typeof enrollFrameSchema>;
