#!/usr/bin/env bash
#
# Print a sha256 manifest of a built `dist/` — one `<sha256>  <path>` line per file, paths relative
# to the dist root, sorted by path so the output is byte-stable and diffable.
#
#   bash deploy/bundle-manifest.sh dist
#
# Deliberately `sha256sum`-compatible: `cd dist && sha256sum -c manifest.txt` checks a local tree with
# no bespoke tooling, and `deploy/verify-bundle.sh` uses the same format for a LIVE site.
#
# Used by deploy/deploy-frontend.sh (what this host published) and by .github/workflows/ci.yml (what
# an independent machine built from the same commit). Those two outputs are meant to be IDENTICAL —
# that equality is the entire claim, so it is generated by one script rather than two.
set -euo pipefail

DIST="${1:-dist}"
[ -d "$DIST" ] || { echo "bundle-manifest: no such directory: $DIST" >&2; exit 1; }

# `find | sort` rather than a glob: the tree is nested (assets/) and the order must not depend on the
# filesystem. LC_ALL=C so the sort is byte-order, not locale-order — a manifest that sorts differently
# on two machines would look like a mismatch when nothing changed.
cd "$DIST"
find . -type f -printf '%P\n' | LC_ALL=C sort | while IFS= read -r f; do
  printf '%s  %s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$f"
done
